server:
  port: 8100
  max-http-request-header-size: 2048KB
  tomcat:
    connection-timeout: 30000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
  messages:
    basename: i18n/lic,i18n/core,i18n/permissions
    encoding: UTF-8
  flyway:
    enabled: true
    table: de_standalone_version
    validate-on-migrate: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  application:
    name: de-server
  main:
    allow-circular-references: true
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache/ehcache.xml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
  jackson:
    parser:
      allow-numeric-leading-zeros: true
management:
  health:
    redis:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
  file:
    path: ./dataease
# sql日志生产环境注释掉
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

quartz:
  enabled: true
  scheduler-name: deSyncJob

dataease:
  version: '@project.version@'
  apisix-api:
    domain: http://192.168.0.121:9180
    key: edd1c9f034335f136f87ad84b625c8f1

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: false






